# This file is generated by composer-plugin-nixify.
# Manual changes might be lost - proceed with caution!

{ lib, php, phpPackages, unzip, stdenv, runCommandLocal, writeText, fetchurl

# Default fetcher.
, fetcher ? (args: fetchurl { inherit (args) name urls sha256; })

}: src:

with lib;

let

  composerPath = phpPackages.composer.src;
  cacheEntries = [
    { name = "composer_installers-1.12.0.0"; filename = "composer/installers/e96bad3e86bc0d257802a8b50035d47cac50c0e7.zip"; sha256 = "0c8fcdd9dc87a92a5961177ea40d1899df9d7a85767e450540f3bc5ed9706ce6"; urls = [ "https://api.github.com/repos/composer/installers/zipball/d20a64ed3c94748397ff5973488761b22f6d3f19" ]; }
    { name = "composer_semver-1.7.2.0"; filename = "composer/semver/e01ecfbcfa44741c2f40fbd0949233048f809a56.zip"; sha256 = "b9fc779bf631a4e61de65490284a5b114ef33c4c84225880a2168f05d619bd99"; urls = [ "https://api.github.com/repos/composer/semver/zipball/647490bbcaf7fc4891c58f47b825eb99d19c377a" ]; }
    { name = "cssjanus_cssjanus-1.3.0.0"; filename = "cssjanus/cssjanus/75996eb22057cdbf9f584ff095eb320131fd7c5b.zip"; sha256 = "fbd6b45df37ed265870a13e4473100f260779932412f54da827555caf5178699"; urls = [ "https://api.github.com/repos/cssjanus/php-cssjanus/zipball/93db9fb39c2f9bcf287715ae254c088b14a77799" ]; }
    { name = "data-values_common-1.0.0.0"; filename = "data-values/common/339207f9ae26813a96703592966702b8eb53b2bc.zip"; sha256 = "2b9a37ba6751270179f5a38a140509e5026f19437be83bb9a2ed4615b45833c2"; urls = [ "https://api.github.com/repos/DataValues/Common/zipball/315bd95ef8e5c360ce8a1cf02c0eef35bbb92561" ]; }
    { name = "data-values_data-values-3.0.0.0"; filename = "data-values/data-values/1e3a7083361b7a62e057e0c63208e2de056ddf6f.zip"; sha256 = "d085b647237d36c2d049917c117c6b1cf0e0f449ea53af060a35eb8af19cef25"; urls = [ "https://api.github.com/repos/DataValues/DataValues/zipball/63dee286f8bb4ae7899c2d2e8d439e7b5332cc49" ]; }
    { name = "data-values_geo-4.3.0.0"; filename = "data-values/geo/c93bb4f44bb97c8a125f07327a1c24fa27c79509.zip"; sha256 = "a52f35e79ba0b4b51211b0380a368d9aea74b12b291a4408f7352e46398074e8"; urls = [ "https://api.github.com/repos/DataValues/Geo/zipball/58fe0a1d027fce6feddbbe97d04678c6b2e40f17" ]; }
    { name = "data-values_interfaces-1.0.0.0"; filename = "data-values/interfaces/e6040c4566238b8401fa2f1f33fcda4ecf761525.zip"; sha256 = "2515f271db08453d3a6461787acfe49f2bb794043ea6453d987960f58316b8a5"; urls = [ "https://api.github.com/repos/DataValues/Interfaces/zipball/244d078954bc05edf8f8c6b088e848289171c3a8" ]; }
    { name = "data-values_validators-1.0.0.0"; filename = "data-values/validators/8adddcdccf6bf7c66d33cb760b9bc8036b12cebe.zip"; sha256 = "d0df551be9571ee97b14c520e65a704d1ed3d8cb24c5cb0437501eedb9ce52fc"; urls = [ "https://api.github.com/repos/DataValues/Validators/zipball/83dbac2c5e9442e8fa2119c8b941ecb88156abe8" ]; }
    { name = "guzzlehttp_guzzle-6.5.5.0"; filename = "guzzlehttp/guzzle/ffb436dc22026b8a4bef580a1fdd8f5931544592.zip"; sha256 = "4b366483f03366d08c0976ecdf00981448a163441ebe717a65e30440e36d99b6"; urls = [ "https://api.github.com/repos/guzzle/guzzle/zipball/9d4290de1cfd701f38099ef7e183b64b4b7b0c5e" ]; }
    { name = "guzzlehttp_promises-1.5.1.0"; filename = "guzzlehttp/promises/4387746adaf4b82103267bd305f9cd3e1e2e56be.zip"; sha256 = "a6b87cdb420aec260041b60691367402ba2c047e1bf6e1b5607725e2cf893b26"; urls = [ "https://api.github.com/repos/guzzle/promises/zipball/fe752aedc9fd8fcca3fe7ad05d419d32998a06da" ]; }
    { name = "guzzlehttp_psr7-1.8.5.0"; filename = "guzzlehttp/psr7/17ab8f327b77285449dccec1fe2e0f82ff608cc1.zip"; sha256 = "373d7724a2277d079ab0ecfc08d549a6d05160e25b3d588ea8ad14ae046ff462"; urls = [ "https://api.github.com/repos/guzzle/psr7/zipball/337e3ad8e5716c15f9657bd214d16cc5e69df268" ]; }
    { name = "jeroen_file-fetcher-6.0.0.0"; filename = "jeroen/file-fetcher/e8bbaf1167b44de05e72a90aec61ad29728efc13.zip"; sha256 = "adcde72372ffc59801faaa38a80ba724e39bab853e042df9a3bb6e0fa8326f21"; urls = [ "https://api.github.com/repos/JeroenDeDauw/FileFetcher/zipball/7a17d947e268e351efc42386d4454a41b07ad481" ]; }
    { name = "justinrainbow_json-schema-5.2.11.0"; filename = "justinrainbow/json-schema/97621cc769aab33b755af4579eb7d2dda2842a7b.zip"; sha256 = "8f4738eeed79ffd905507e608252dcfec5e8fd9594fcb724c4d63338100fd155"; urls = [ "https://api.github.com/repos/justinrainbow/json-schema/zipball/2ab6744b7296ded80f8cc4f9509abbff393399aa" ]; }
    { name = "liuggio_statsd-php-client-1.0.18.0"; filename = "liuggio/statsd-php-client/a41b3ca5c968f6d88436f5dcdef6cd7100fd6e4f.zip"; sha256 = "38891395130ba14f0ae57477d0d98261cda80596d0bb9d2b90674ab2f1dc9f86"; urls = [ "https://api.github.com/repos/liuggio/statsd-php-client/zipball/c42e6d6687b7b2d7683186ec7f4f03351cc3dbca" ]; }
    { name = "mediawiki_page-forms-5.3.4.0"; filename = "mediawiki/page-forms/cc655e2b35ce7005b1ec907081cf42b2cd0d6e97.zip"; sha256 = "ea6eb1413dda9b716d51346976e2fdf22198bb7fec00c2ffdc36fa0e83c713a4"; urls = [ "https://api.github.com/repos/wikimedia/mediawiki-extensions-PageForms/zipball/b9a4c1d8b8151611bc04bd7331d8b686e55e04af" ]; }
    { name = "mediawiki_parser-hooks-1.6.1.0"; filename = "mediawiki/parser-hooks/91fcc3df3a4bf4b15e3828b403a698bdc03ba21e.zip"; sha256 = "2b77328a8b8db22dde2195b02b972cc00d79eaab6c65cf7249fd028afd583f20"; urls = [ "https://api.github.com/repos/JeroenDeDauw/ParserHooks/zipball/45660efef737bcf33abbbb12c1ddb049c4e713fe" ]; }
    { name = "mediawiki_semantic-media-wiki-4.0.1.0"; filename = "mediawiki/semantic-media-wiki/d279c048edf46dd26112bf3f7870ba63e5370a0b.zip"; sha256 = "bb1532aa8f34ea7bc8b2699961de73cb45869875bc2ea484c6bc844764b5990f"; urls = [ "https://api.github.com/repos/SemanticMediaWiki/SemanticMediaWiki/zipball/fd1b241a46341786d538c20112bf7132d8279398" ]; }
    { name = "mediawiki_semantic-result-formats-4.0.1.0"; filename = "mediawiki/semantic-result-formats/4409ac59379d4176266c2ae881302ce189071a79.zip"; sha256 = "1fefb1970700e0e388dc1fc385e8390bbed6efac78dbc97e589e0b6c0d3705f2"; urls = [ "https://api.github.com/repos/SemanticMediaWiki/SemanticResultFormats/zipball/44c0bd85f89a2dfd72327fe742740895d7f32b11" ]; }
    { name = "nicmart_tree-0.2.7.0"; filename = "nicmart/tree/e6b5bf7d9c503aac58f4ef5b98b11bef4ea9afb9.zip"; sha256 = "b7d2b2e44b706bed8cf5972e036893d81d5c14187fbdf2bda02c7f7b802e70e2"; urls = [ "https://api.github.com/repos/nicmart/Tree/zipball/0616b54bb49938e1a816141d7943db48ebf76938" ]; }
    { name = "onoi_blob-store-1.2.1.0"; filename = "onoi/blob-store/ef7d2cecf87237e3a3b4a87d06f5c5429375d870.zip"; sha256 = "9510a94afd9711ba3fe1db1d4968fc792eda6a87488b8705ad38c59400ac387b"; urls = [ "https://api.github.com/repos/onoi/blob-store/zipball/c3e1f15214977e904fc0e91e0480175a464977ce" ]; }
    { name = "onoi_cache-1.2.0.0"; filename = "onoi/cache/f8608503c063f59361bd0318c8538c7b8e06429e.zip"; sha256 = "460ca160279d219a04e1041705cd3c03a34baea60d7f5f96fb9302e4159dacda"; urls = [ "https://api.github.com/repos/onoi/cache/zipball/ecc999186aab7c8db411aedd892b2e5fe5a0b422" ]; }
    { name = "onoi_callback-container-2.0.0.0"; filename = "onoi/callback-container/8df674dfa239f1eaac7e53d4aff9926231bb86c3.zip"; sha256 = "019542250137cb4951b8ac073b54753747735ac327f686cf1e571f73228f1c33"; urls = [ "https://api.github.com/repos/onoi/callback-container/zipball/cf2f4dda1b2479bc786985fdb5554af528d03e52" ]; }
    { name = "onoi_event-dispatcher-1.1.0.0"; filename = "onoi/event-dispatcher/fb17afa375e117410700133e873be02fefacf752.zip"; sha256 = "40bbc9997c5fec23fd077de4af16aac51c0bc597d328685c217086565980eb16"; urls = [ "https://api.github.com/repos/onoi/event-dispatcher/zipball/2af64e3997fc59b6d1e1f8f77e65fd6311c37109" ]; }
    { name = "onoi_http-request-1.3.1.0"; filename = "onoi/http-request/bbb11ce7867529601325287b74b9c9fb3a7c47a2.zip"; sha256 = "7f06863a340185e9f23f3f0e50f9ec195ae7a863cd7e9543030ae415ecb22c4a"; urls = [ "https://api.github.com/repos/onoi/http-request/zipball/a7cf33bae82cffe570086fc06d6617e802c0cc74" ]; }
    { name = "onoi_message-reporter-1.4.2.0"; filename = "onoi/message-reporter/cd49ea2c68ef34e2680471c4ed3153246bb1704a.zip"; sha256 = "8937965584e7b01f8a5c4047c61151d31833e1f4a61eb26248cca535022f01aa"; urls = [ "https://api.github.com/repos/onoi/message-reporter/zipball/ead8ef8f2868ccee6881e471295ebbaf8428c96c" ]; }
    { name = "onoi_shared-resources-0.4.3.0"; filename = "onoi/shared-resources/f13d488e2f521c6f355eb503dda4ccb7ac8088ef.zip"; sha256 = "07f2c8cfcb689b22708c631964c64481e13cc5dbdd4d16fe9915e61ba02e8943"; urls = [ "https://api.github.com/repos/onoi/shared-resources/zipball/322273a7462eb0c15305dde9207138f00a387080" ]; }
    { name = "oojs_oojs-ui-0.39.3.0"; filename = "oojs/oojs-ui/94170a6d320cbbfeb62e5caf4c084df67c612bbc.zip"; sha256 = "ae1de305e5b42ff4186b58f53c0c0cb089e7ebc9dcd4395a276a1fbde3118e7d"; urls = [ "https://api.github.com/repos/wikimedia/oojs-ui/zipball/517e59fe02a6857c35220094b8ece47800a7344e" ]; }
    { name = "param-processor_param-processor-1.12.0.0"; filename = "param-processor/param-processor/51152a37fc5d6f32adc7df9112dd87463309e3b3.zip"; sha256 = "d4838fc78c398994aff02a0fccf28b57d02249f1bef191c5d13d12eac4390e0b"; urls = [ "https://api.github.com/repos/JeroenDeDauw/ParamProcessor/zipball/0850dc2af72d31b8f645e0f87a44ff4b68583a64" ]; }
    { name = "pear_console_getopt-1.4.3.0"; filename = "pear/console_getopt/7dfb60dd14495e47f9e14d051b6f01a660ece167.zip"; sha256 = "b4eed79039bc4d20e59d540bb85396666445b8c6a6bd1bc04017cca49bd2169c"; urls = [ "https://api.github.com/repos/pear/Console_Getopt/zipball/a41f8d3e668987609178c7c4a9fe48fecac53fa0" ]; }
    { name = "pear_mail-1.4.1.0"; filename = "pear/mail/f603cda49d52c87dde18ca4e207d55c78a75ecb2.zip"; sha256 = "4242fb207ddca0577049409efda9c056ef3668144f9ac860c3ddc05c8c30893f"; urls = [ "https://api.github.com/repos/pear/Mail/zipball/9609ed5e42ac5b221dfd9af85de005c59d418ee7" ]; }
    { name = "pear_mail_mime-1.10.11.0"; filename = "pear/mail_mime/1aff578fbf52abc0259e23d25990803fe9566936.zip"; sha256 = "421039dd2e0b0e051d359fc1b12bd0bf7cbeea9a3ce217237387a5aa274ff074"; urls = [ "https://api.github.com/repos/pear/Mail_Mime/zipball/d4fb9ce61201593d0f8c6db629c45e29c3409c14" ]; }
    { name = "pear_net_smtp-1.9.1.0"; filename = "pear/net_smtp/66164e8e0b2c788be74f31e8872f584e98b62fc3.zip"; sha256 = "3d74af0ce4e26fc7c10cc5222cf673843aac6a79ec279facc01b3115a1e5b8c5"; urls = [ "https://api.github.com/repos/pear/Net_SMTP/zipball/ee0e156ab94b37ac7ad10623a4a62f10a2a2d421" ]; }
    { name = "pear_net_socket-1.2.2.0"; filename = "pear/net_socket/411889a8f22340055fe5b7865ba6beff110a77b2.zip"; sha256 = "80a2b19023a161911af8f9cc561fe52ce31ffbf4238b9b6061875852e438c64a"; urls = [ "https://api.github.com/repos/pear/Net_Socket/zipball/bbe6a12bb4f7059dba161f6ddd43f369c0ec8d09" ]; }
    { name = "pear_pear-core-minimal-1.10.11.0"; filename = "pear/pear-core-minimal/7b54f786508ffd8c3fb271aefe91225f35d7bdab.zip"; sha256 = "f838013a20895f744cd58a91112a3f9ba8b76cf1ef655363c0da94698eec613e"; urls = [ "https://api.github.com/repos/pear/pear-core-minimal/zipball/68d0d32ada737153b7e93b8d3c710ebe70ac867d" ]; }
    { name = "pear_pear_exception-1.0.2.0"; filename = "pear/pear_exception/c6c1b248c4f91b0f5a9c73f5c701d341bdf0de4d.zip"; sha256 = "6971a771990ae8081d2b0f1c2126447684e92ace553a9003e5651afec2e3f64d"; urls = [ "https://api.github.com/repos/pear/PEAR_Exception/zipball/b14fbe2ddb0b9f94f5b24cf08783d599f776fff0" ]; }
    { name = "pleonasm_bloom-filter-1.0.2.0"; filename = "pleonasm/bloom-filter/3e2942e338c7709299760994582aec9a8c05ba4f.zip"; sha256 = "897c1f8ff963d31ce73fd445216b87dab42df4daf8b9495aa9ad2d8cec72a571"; urls = [ "https://api.github.com/repos/pleonasm/bloom-filter/zipball/4a3292c9f83a778c44271bf4e4f6be1204b87f7b" ]; }
    { name = "psr_container-1.0.0.0"; filename = "psr/container/9bd0b358d39e22d7d8d7a342efcb207f3ae9a84d.zip"; sha256 = "92786662ffa29e766ef47b00d6021d29718b89576fd39940740f2cfe36317f66"; urls = [ "https://api.github.com/repos/php-fig/container/zipball/b7ce3b176482dbbc1245ebf52b181af44c2cf55f" ]; }
    { name = "psr_http-message-1.0.1.0"; filename = "psr/http-message/cc1d4e9ee13f2053b80c08976256789bf3be5256.zip"; sha256 = "8538467ca2665fe15574f4d2506871823f71fd24b9a9284aae2ba90d8f69ada4"; urls = [ "https://api.github.com/repos/php-fig/http-message/zipball/f6561bf28d520154e4b0ec72be95418abe6d9363" ]; }
    { name = "psr_log-1.1.3.0"; filename = "psr/log/eba32e017e823df412a2fcdb3e04b6766157b3ad.zip"; sha256 = "240ba289e5815e165c58abcb4bf91b47c5740ebaaf87df9b26946242df4bf1da"; urls = [ "https://api.github.com/repos/php-fig/log/zipball/0f73288fd15629204f9d42b7055f72dacbe811fc" ]; }
    { name = "ralouphie_getallheaders-3.0.3.0"; filename = "ralouphie/getallheaders/ddc5f4c7ab3d868f5060717336a0d93475d53175.zip"; sha256 = "ef0165da5690da666ab4cb88bb4cec0d50372e3e7c922532c5795a3567b367af"; urls = [ "https://api.github.com/repos/ralouphie/getallheaders/zipball/120b605dfeb996808c31b6477290a714d356e822" ]; }
    { name = "seld_jsonlint-1.8.3.0"; filename = "seld/jsonlint/95b357497b2b109875d7f07118aabe672408722a.zip"; sha256 = "17498c06edd3eec4f3562b50f2f78572b41e3108c7ad8b0fd44bc47fe28896fb"; urls = [ "https://api.github.com/repos/Seldaek/jsonlint/zipball/9ad6ce79c342fbd44df10ea95511a1b24dee5b57" ]; }
    { name = "serialization_serialization-4.0.0.0"; filename = "serialization/serialization/830c9792e14955bffb82658a89ebe66549f8d7e5.zip"; sha256 = "be3438dda21c9a6be9ef9f6c20b46b46e2a23c7f6a3eee29669ec0749e383e65"; urls = [ "https://api.github.com/repos/wmde/Serialization/zipball/6fa293415e2b70c30c1e673d8bcd04d27dc15e44" ]; }
    { name = "stephank_composer-plugin-nixify-1.1.0.0"; filename = "stephank/composer-plugin-nixify/6b00aedf28221acbb64a87222a0eb819404901f2.zip"; sha256 = "ac7cc480698f8717fb9fce4077b81303d37fe6ab2b89c8547cd7f9451598ee1e"; urls = [ "https://api.github.com/repos/stephank/composer-plugin-nixify/zipball/d93c4348388d714d7d81b41e34ccb2ae9c2131c2" ]; }
    { name = "symfony_css-selector-3.4.47.0"; filename = "symfony/css-selector/85ffc60d7210c955bfaabc4e35acd19eb087ef73.zip"; sha256 = "42d119cced944af769ba396c50aee1225b7f4f365e06c7c1ee120516d89f3d5a"; urls = [ "https://api.github.com/repos/symfony/css-selector/zipball/da3d9da2ce0026771f5fe64cb332158f1bd2bc33" ]; }
    { name = "symfony_polyfill-intl-idn-1.25.0.0"; filename = "symfony/polyfill-intl-idn/dc5c9eacfdc9c87d5291bd410f0c602b4fe69802.zip"; sha256 = "76bd07166f46332146d702b2aa6d32b18c0e84ad639faed6f7fdf6722dfd215a"; urls = [ "https://api.github.com/repos/symfony/polyfill-intl-idn/zipball/749045c69efb97c70d25d7463abba812e91f3a44" ]; }
    { name = "symfony_polyfill-intl-normalizer-1.25.0.0"; filename = "symfony/polyfill-intl-normalizer/ff87d413e80cc4de92c8063abce356b5b870b37c.zip"; sha256 = "036a4eaf320e52e8f987ac6c134c9c1cc362efedf445e5d7130d60006cecc0b0"; urls = [ "https://api.github.com/repos/symfony/polyfill-intl-normalizer/zipball/8590a5f561694770bdcd3f9b5c69dde6945028e8" ]; }
    { name = "symfony_polyfill-php72-1.25.0.0"; filename = "symfony/polyfill-php72/df02f6e02ca2caac31185a1ded4d22665035faa2.zip"; sha256 = "0b09d2462f61bdf0f23b46865ff4967fff05fce32e7de154deefcb9e375b371a"; urls = [ "https://api.github.com/repos/symfony/polyfill-php72/zipball/9a142215a36a3888e30d0a9eeea9766764e96976" ]; }
    { name = "symfony_polyfill-php80-1.25.0.0"; filename = "symfony/polyfill-php80/fd8f078da708ad465154268956bfaf35078daf8c.zip"; sha256 = "ce35a9bb3ce1c54f08736f5b68f89903cea268fd065e395b033a27daed84fca0"; urls = [ "https://api.github.com/repos/symfony/polyfill-php80/zipball/4407588e0d3f1f52efb65fbe92babe41f37fe50c" ]; }
    { name = "wikimedia_assert-0.5.0.0"; filename = "wikimedia/assert/46579775d7169b2d98ea0d99c83da6a0f2a10376.zip"; sha256 = "09e638e948589e6c0c2d6f65d77e39cf5af1900b9727487215265b51c8fc17cc"; urls = [ "https://api.github.com/repos/wikimedia/Assert/zipball/d8e97f15b8f3d3799899e3d56452d34511be5764" ]; }
    { name = "wikimedia_at-ease-2.0.0.0"; filename = "wikimedia/at-ease/5eb87a86db889a609ef4520750feef4f4fb99eb8.zip"; sha256 = "1a05ac98f48577b0a6c10ad54d2388f4f88852f07a2d9c7b102459ef4478a510"; urls = [ "https://api.github.com/repos/wikimedia/at-ease/zipball/013ac61929797839c80a111a3f1a4710d8248e7a" ]; }
    { name = "wikimedia_base-convert-2.0.1.0"; filename = "wikimedia/base-convert/3b1e6e6f58c062d288ec59cce83cd758d75a9c70.zip"; sha256 = "344ffcd0c2e7cd33a307e8dd0005ab86ccc31ac8147f6d84086ae443db4ec665"; urls = [ "https://api.github.com/repos/wikimedia/base-convert/zipball/449f0d0237cf1e0e71faec90680c88d4af6e711d" ]; }
    { name = "wikimedia_cdb-1.4.1.0"; filename = "wikimedia/cdb/bd8acb35562bd78836daf0a5f69fcc10b1eb3844.zip"; sha256 = "ac9159ad1fefc3e67b10123cef94be7e4d13b7507500587412505ad28c48b879"; urls = [ "https://api.github.com/repos/wikimedia/cdb/zipball/d49d96232f045311dc1f21bf0d7e40adf82a1f1d" ]; }
    { name = "wikimedia_cldr-plural-rule-parser-1.0.0.0"; filename = "wikimedia/cldr-plural-rule-parser/2543d4ab7694faa40549c58f502122462ec60fe9.zip"; sha256 = "9ba32cf21d62a16a6e7421cf5adf24540924fa9d2ed3d637314e45041d7f7108"; urls = [ "https://api.github.com/repos/wikimedia/CLDRPluralRuleParser/zipball/2b623a411b1a8efa4363e9fda9da496ab83a5d69" ]; }
    { name = "wikimedia_common-passwords-0.2.0.0"; filename = "wikimedia/common-passwords/a6417ccce10b3d302f9cf0051da53cfb548398c5.zip"; sha256 = "2ad06f2f9840c1413597e5c0929e230b36fd80ff1593519faaf6feef8401cc60"; urls = [ "https://api.github.com/repos/wikimedia/common-passwords/zipball/b9db612730d427a55e28f4a9b143b87fd72173e0" ]; }
    { name = "wikimedia_composer-merge-plugin-2.0.1.0"; filename = "wikimedia/composer-merge-plugin/2280be3bb7786b86b11c6715964f099a2891b016.zip"; sha256 = "e1627388f499eaaf29df45fdcf2e3ebba7282b66d02590f874bf5c018eba9e46"; urls = [ "https://api.github.com/repos/wikimedia/composer-merge-plugin/zipball/8ca2ed8ab97c8ebce6b39d9943e9909bb4f18912" ]; }
    { name = "wikimedia_html-formatter-2.0.1.0"; filename = "wikimedia/html-formatter/af03c8bab537658141d6b3b044fa32a613b360dd.zip"; sha256 = "a82ef02f4380b02aab42af00be3e20f7da389d7ec25f902e163845e0da5f6e40"; urls = [ "https://api.github.com/repos/wikimedia/html-formatter/zipball/3abeb56b30f436a486735ca53f6af0ba6367e4cf" ]; }
    { name = "wikimedia_ip-set-2.1.0.0"; filename = "wikimedia/ip-set/bd0707da770e431b04b9710d752b46d07585e29a.zip"; sha256 = "7698b96d8180d6a49d2225277af1b696e5eceb2dcdf5dddec7d13656624636ab"; urls = [ "https://api.github.com/repos/wikimedia/IPSet/zipball/f84555041a405f0ea51c64a0c7fb5fac36e99b84" ]; }
    { name = "wikimedia_ip-utils-1.0.0.0"; filename = "wikimedia/ip-utils/c8726d2ac9de517f2fa6d391bc428b9d26aedfb1.zip"; sha256 = "2983772246ed33955733002885a8309c9160070483d31b24af7c7914d2f78738"; urls = [ "https://api.github.com/repos/wikimedia/mediawiki-libs-IPUtils/zipball/c505b99c0dfab12254d64a5e064bddd13cf066ad" ]; }
    { name = "wikimedia_less.php-3.1.0.0"; filename = "wikimedia/less.php/c232fd65ec2d5a1634d505cd8a34c29e252207f5.zip"; sha256 = "c6ba79b353cd6647bb2b25e862f38430f90e3224bf9cb646f6539cfd83f36d64"; urls = [ "https://api.github.com/repos/wikimedia/less.php/zipball/a486d78b9bd16b72f237fc6093aa56d69ce8bd13" ]; }
    { name = "wikimedia_object-factory-2.2.0.0"; filename = "wikimedia/object-factory/25de2cbec8dd421f7771d28df67c43424ab2ce6e.zip"; sha256 = "cd997b9d12157f993f058b3773267d3c2e3b0e022a57ac62e5aad5aa3fb488e5"; urls = [ "https://api.github.com/repos/wikimedia/object-factory/zipball/d2e8cba4c8d98c29f6dd2f93cf19b0792dd83d42" ]; }
    { name = "wikimedia_parsoid-0.12.2.0"; filename = "wikimedia/parsoid/59ca97c267c078353e4c649549e4d4d64b0d0ccb.zip"; sha256 = "1229f8723b119703c863d62cdac6e93c8dcff0eb06b92394df9a8deecef2a62f"; urls = [ "https://api.github.com/repos/wikimedia/parsoid/zipball/15169a678f9f468ff6465035a32f28e8ec82003f" ]; }
    { name = "wikimedia_php-session-serializer-1.0.7.0"; filename = "wikimedia/php-session-serializer/7c01d4f5ae3619ed3b976e405cc072e31651fe24.zip"; sha256 = "75c107e01d87863b7854adb59d38167ab0b41c6806fc03af79f5c53841fd5bad"; urls = [ "https://api.github.com/repos/wikimedia/php-session-serializer/zipball/9382814e701c94358ae02f3260b7ac4951385d83" ]; }
    { name = "wikimedia_purtle-1.0.7.0"; filename = "wikimedia/purtle/3baf20dabe3233f826ce5ed35867995fbefe8c41.zip"; sha256 = "6ae66bfbd3876fdc439bef1dba8d6fb372c8ebac41c84191bc0d1b583fc7aa77"; urls = [ "https://api.github.com/repos/wikimedia/purtle/zipball/569064c065caae036cd5a685574b6f96f05cfe33" ]; }
    { name = "wikimedia_relpath-2.1.1.0"; filename = "wikimedia/relpath/464ae80208debb6b5867658f63ecb2b03bfb6fbe.zip"; sha256 = "60a30bcf630d20c70d5acee4e6df90e2c52ad0262941ae0b65b9bb5483bb4e59"; urls = [ "https://api.github.com/repos/wikimedia/RelPath/zipball/35e701ff16abf461bb8676a9d9177f86fa0b2c94" ]; }
    { name = "wikimedia_remex-html-2.2.0.0"; filename = "wikimedia/remex-html/5f84cfdd45fc3766f51ee9782f18bf91644abdb0.zip"; sha256 = "370dc37f192283457834d52a5d04fbd83062876899966194a98cbd7ecedd72ae"; urls = [ "https://api.github.com/repos/wikimedia/remex-html/zipball/7792461b0605b1fcd4bba47bf54cdc64790edb48" ]; }
    { name = "wikimedia_running-stat-1.2.1.0"; filename = "wikimedia/running-stat/98bf2a7aa2d9757afcaa6f06ef2b9031d37bba3d.zip"; sha256 = "ecd2b07c45c3097cfe3d8028c72c7e762f460056dea9384a491f782412f6a8cc"; urls = [ "https://api.github.com/repos/wikimedia/RunningStat/zipball/60eebada7cc64b7073d90e7d4bab00efaafa0ba9" ]; }
    { name = "wikimedia_scoped-callback-3.0.0.0"; filename = "wikimedia/scoped-callback/e4ad5aaad0c53070e3f259a1bb8996749c97ea1f.zip"; sha256 = "66a7f59875726614a3b8927c14856477d68edd26b0a7812fe8c1d4ac6f9b6e48"; urls = [ "https://api.github.com/repos/wikimedia/ScopedCallback/zipball/0a480d9a9772634697c77598726cf24606597bd0" ]; }
    { name = "wikimedia_services-2.0.1.0"; filename = "wikimedia/services/d7e5df44843d75139e6303c1d397bcba73208931.zip"; sha256 = "90019775b656d64aa4b2075dc63df4a29f2ce786bb9a1e052918207149271ccf"; urls = [ "https://api.github.com/repos/wikimedia/mediawiki-libs-Services/zipball/5ef69a8a8b0d2ea115d08469bdab468f58fac820" ]; }
    { name = "wikimedia_textcat-2.0.0.0"; filename = "wikimedia/textcat/e7e3c5de91307063c6991fa133f1d1eeb4790cfd.zip"; sha256 = "b52c01cd152093660544f90148f2fef26a1fe9ff416118f0a131ce688a736abe"; urls = [ "https://api.github.com/repos/wikimedia/textcat/zipball/dfdfb1c41bb016814a9d4da3aa68b62437b54a82" ]; }
    { name = "wikimedia_timestamp-3.0.0.0"; filename = "wikimedia/timestamp/f228731a72376c8e04508e796aa9409a11675de3.zip"; sha256 = "c42cf422a932f09f04c811e9e3d925e95cda92495163f5dca3b9a892cd48ae10"; urls = [ "https://api.github.com/repos/wikimedia/Timestamp/zipball/42ce5586d2189826e28ebcf4cedc96226b6d77e2" ]; }
    { name = "wikimedia_utfnormal-2.0.0.0"; filename = "wikimedia/utfnormal/824487fcaf277436abe971d7b998fde9a3df0f8d.zip"; sha256 = "50afe3844ac42a29539e08051e6320003fc29c828231ecec7271e2b1d735bb3e"; urls = [ "https://api.github.com/repos/wikimedia/utfnormal/zipball/ec1ec7ce9e25cd275c532afd30bb6092a7633990" ]; }
    { name = "wikimedia_wait-condition-loop-1.0.1.0"; filename = "wikimedia/wait-condition-loop/04b8263f9e182fb8b0472e01a12b82e6effbfb1f.zip"; sha256 = "e4f1871ad4daf885331668e57895d0ba282f917061cf4e16ffc3996d941e7dc2"; urls = [ "https://api.github.com/repos/wikimedia/wait-condition-loop/zipball/0321b8ca6a0f701f96e04e5e8e6d3e244ab05338" ]; }
    { name = "wikimedia_wikipeg-2.0.6.0"; filename = "wikimedia/wikipeg/65976eb3de1ae2886748090768ff9c3be9ba3006.zip"; sha256 = "aadd5fcba8ae51b1749a7f1c222436ab1d1bfd01e949a73d7639f026b350b6bd"; urls = [ "https://api.github.com/repos/wikimedia/wikipeg/zipball/9a92384ae11e1a3b7ecfe0feef1809b1af73889b" ]; }
    { name = "wikimedia_wrappedstring-3.2.0.0"; filename = "wikimedia/wrappedstring/880b0cac872a35d2bb362b94a2f0d630d688993b.zip"; sha256 = "e9ca6c62a194ad0e55059b1751bf94b688f41dd93ddf9f0ffcd70153f7bbcf71"; urls = [ "https://api.github.com/repos/wikimedia/WrappedString/zipball/11b01a2286fd377cb15c2f5561e10f56d58f37a9" ]; }
    { name = "wikimedia_xmp-reader-0.7.0.0"; filename = "wikimedia/xmp-reader/b71c45eb2c16f801f8142aa596446f96a3a0b382.zip"; sha256 = "1470249e754fb8e2dbbeda54615350b9a8575b5905c85c2f26cbabac22e56287"; urls = [ "https://api.github.com/repos/wikimedia/xmp-reader/zipball/4b8ab8ea23cc2ccf2530738081cb4e146d55b86b" ]; }
    { name = "wikimedia_zest-css-1.1.5.0"; filename = "wikimedia/zest-css/a9a021151596623858cb6ad27d7956dd02c67c16.zip"; sha256 = "da8bab76280b3059aebc93076608cb39cb689e73a446e00a73d5ce3e8ac87c86"; urls = [ "https://api.github.com/repos/wikimedia/mediawiki-libs-Zest/zipball/bc3346fcf2a93f02a8a6697d98c305c14ef1869f" ]; }
    { name = "zordius_lightncandy-1.2.5.0"; filename = "zordius/lightncandy/411809a230214c2e2c3f2a8c1caae22816fe0100.zip"; sha256 = "7f0a10197663cc30d2192583dba1b4f712a7aacab966dec50622e4569b752ecb"; urls = [ "https://api.github.com/repos/zordius/lightncandy/zipball/37aa381e0f27d411a630062070c7a5a2174c62e7" ]; }
    { name = "composer_package-versions-deprecated-1.11.99.5"; filename = "composer/package-versions-deprecated/7696d631625b248d150b3db3037b6fb36a2f1cf1.zip"; sha256 = "557187e1f72faff2b2e61fedd93824c74b491f6078c8135fe2978488e6ee32c3"; urls = [ "https://api.github.com/repos/composer/package-versions-deprecated/zipball/b4f54f74ef3453349c24a845d22392cd31e65f1d" ]; }
    { name = "composer_spdx-licenses-1.5.3.0"; filename = "composer/spdx-licenses/0dfa6782d547a994fa1c2ddd70373502c43e02f4.zip"; sha256 = "747a64d1cdbcb051075cac7b72c52dfa74f28386e5ea7ea8c3c3f8659f8b8b85"; urls = [ "https://api.github.com/repos/composer/spdx-licenses/zipball/0c3e51e1880ca149682332770e25977c70cf9dae" ]; }
    { name = "composer_xdebug-handler-1.4.6.0"; filename = "composer/xdebug-handler/abc1c1b9a349e885d11f6dda6db0de9578c77c57.zip"; sha256 = "1017e601bc8dacd992a9410c948a3e4eb6ec19081611b54ec1c4b17f9c4f6435"; urls = [ "https://api.github.com/repos/composer/xdebug-handler/zipball/f27e06cd9675801df441b3656569b328e04aa37c" ]; }
    { name = "dnoegel_php-xdg-base-dir-0.1.1.0"; filename = "dnoegel/php-xdg-base-dir/b81b493e09050800919750bdd1e829656fc89971.zip"; sha256 = "d881707cf02a8aa1a1846e0166e0b1704eeacac059f08a7ec48b593e3959c40a"; urls = [ "https://api.github.com/repos/dnoegel/php-xdg-base-dir/zipball/8f8a6e48c5ecb0f991c2fdcf5f154a47d85f9ffd" ]; }
    { name = "doctrine_cache-2.1.1.0"; filename = "doctrine/cache/6b27cfd7d896ab2c16f559f30549947e665011de.zip"; sha256 = "df5b0b4b1e03f9f415b7e8c6ba6f8eca9ddfe6a1c2bf59f0c3b715050c1959cf"; urls = [ "https://api.github.com/repos/doctrine/cache/zipball/331b4d5dbaeab3827976273e9356b3b453c300ce" ]; }
    { name = "doctrine_dbal-3.1.5.0"; filename = "doctrine/dbal/1a9ec752296ea45d1649938403d28c07d275e053.zip"; sha256 = "a523a4b8b4e774f24b6083b5133df1948d85f78167f4dc82bcdae3c1497936f1"; urls = [ "https://api.github.com/repos/doctrine/dbal/zipball/187916074db413f4a070a721c9d30b420a9135dd" ]; }
    { name = "doctrine_deprecations-0.5.3.0"; filename = "doctrine/deprecations/f470effb0c529a4c2103eb2bd5595b1db4768567.zip"; sha256 = "86c6bea7a3358500c5730de0b2d23c07f54e8a7eedbc79758d06f158e65f7712"; urls = [ "https://api.github.com/repos/doctrine/deprecations/zipball/9504165960a1f83cc1480e2be1dd0a0478561314" ]; }
    { name = "doctrine_event-manager-1.1.1.0"; filename = "doctrine/event-manager/f1f7017665be23eb920c9a54d3f7fe51754c08ae.zip"; sha256 = "a892fb0abf560a6fee5cc4a2c2fe421e672f9ea52a65c599337b3b427954c25e"; urls = [ "https://api.github.com/repos/doctrine/event-manager/zipball/41370af6a30faa9dc0368c4a6814d596e81aba7f" ]; }
    { name = "doctrine_instantiator-1.4.1.0"; filename = "doctrine/instantiator/b6977602bc07407dd2e3c71223021731d80df6d6.zip"; sha256 = "e74aae2efad779dc6044b0b5d3ac4cf56eb41a511549ed35e6046cb4d6e0d7d4"; urls = [ "https://api.github.com/repos/doctrine/instantiator/zipball/10dcfce151b967d20fde1b34ae6640712c3891bc" ]; }
    { name = "doctrine_sql-formatter-1.1.0.0"; filename = "doctrine/sql-formatter/698d1a87b0c8fc50604154f1bd358c8e1584b739.zip"; sha256 = "b96ee0fa0a4b01e6ce3ff1c2f09983b7dd6def3e3b3d98a26564597088b814e1"; urls = [ "https://api.github.com/repos/doctrine/sql-formatter/zipball/5458bdcf176f6a53292e3f0cc73f292d6302fb0f" ]; }
    { name = "felixfbecker_advanced-json-rpc-3.2.1.0"; filename = "felixfbecker/advanced-json-rpc/ee93f6a030a8ec4909ae17405ed90c75f9d0c59c.zip"; sha256 = "98b15c828413b99ecd0670f91ee25eea5ac9453d5507b2d63711dabf44982490"; urls = [ "https://api.github.com/repos/felixfbecker/php-advanced-json-rpc/zipball/b5f37dbff9a8ad360ca341f3240dc1c168b45447" ]; }
    { name = "giorgiosironi_eris-0.10.0.0"; filename = "giorgiosironi/eris/2f95e51e4183db71cadeffe8cc224581a00ba162.zip"; sha256 = "920be4afb2f59155d424a4dfa53e56b41674667a00a81ba198c912ca1f0ecf5e"; urls = [ "https://api.github.com/repos/giorgiosironi/eris/zipball/d7cbea45ff7c7621d69589ae7f8a82f183673e69" ]; }
    { name = "hamcrest_hamcrest-php-2.0.1.0"; filename = "hamcrest/hamcrest-php/f7a45641934dde6189dd47e6355c3290a81916b1.zip"; sha256 = "191a65145df949136993b3b512f78f6c492cc8082e35329c193f3845efadb5c7"; urls = [ "https://api.github.com/repos/hamcrest/hamcrest-php/zipball/8c3d0a3f6af734494ad8f6fbbee0ba92422859f3" ]; }
    { name = "johnkary_phpunit-speedtrap-3.3.0.0"; filename = "johnkary/phpunit-speedtrap/b31157817328f2d95d9cafec59ff2a82256e2030.zip"; sha256 = "b4defae6cb94d0c32c54b2d1a73836a6f791346b2cb35a3d5885f82b292e23a2"; urls = [ "https://api.github.com/repos/johnkary/phpunit-speedtrap/zipball/9ba81d42676da31366c85d3ff8c10a8352d02030" ]; }
    { name = "mediawiki_mediawiki-codesniffer-38.0.0.0"; filename = "mediawiki/mediawiki-codesniffer/6592eb9d91c0d3152fa229260f4ec2b6b9f16446.zip"; sha256 = "d3ea1d528afd2d7cf69045e8c7d68cb296e68945990f5479e3f3fedf9b25a836"; urls = [ "https://api.github.com/repos/wikimedia/mediawiki-tools-codesniffer/zipball/059db7ef17adf2fd1088c42a05e6736e5c2aab2a" ]; }
    { name = "mediawiki_mediawiki-phan-config-0.10.6.0"; filename = "mediawiki/mediawiki-phan-config/d978ab06bee9ec9e1c5d372f4da6ff0929639b0b.zip"; sha256 = "2d143a5cfddbc4725f4e05d5baa9c9b50f7425fd14afbfa100003f4c0639c334"; urls = [ "https://api.github.com/repos/wikimedia/mediawiki-tools-phan/zipball/4bb1607bb41dd00b83ee81f7a4deb7889be16ac1" ]; }
    { name = "mediawiki_phan-taint-check-plugin-3.2.1.0"; filename = "mediawiki/phan-taint-check-plugin/40304fd8d725ed9d26d08ac11fe113cdcb29bc87.zip"; sha256 = "6c8d366bd3eeed9f8635fc6046ee3ca1190f07faa214c0064cafa7559257ba47"; urls = [ "https://api.github.com/repos/wikimedia/phan-taint-check-plugin/zipball/4bc471bd790644398a6749eedd7a841e9a759bd6" ]; }
    { name = "microsoft_tolerant-php-parser-0.0.23.0"; filename = "microsoft/tolerant-php-parser/17bc577b794d4bc614547eac00cba58eec39ce9b.zip"; sha256 = "33d602a6b017e8803359c5df1f8b4af6f0302356ddd0843b63c1040a3cd81e36"; urls = [ "https://api.github.com/repos/microsoft/tolerant-php-parser/zipball/1d76657e3271754515ace52501d3e427eca42ad0" ]; }
    { name = "monolog_monolog-2.2.0.0"; filename = "monolog/monolog/1ea03bfb7b8a89de2fcecb0cc0b1204ac14411e0.zip"; sha256 = "53944ad8280d9c36992647572360b8961b57a91cf82a2c5d115c665e7d6cd5bf"; urls = [ "https://api.github.com/repos/Seldaek/monolog/zipball/1cb1cde8e8dd0f70cc0fe51354a59acad9302084" ]; }
    { name = "myclabs_deep-copy-1.11.0.0"; filename = "myclabs/deep-copy/8a47e905abc875fa8049c320097a46a9c305b50b.zip"; sha256 = "3c357c9554caa4d6d71117ce8cfb7db23c1ac64eb28a1e659988cbcf201ba984"; urls = [ "https://api.github.com/repos/myclabs/DeepCopy/zipball/14daed4296fae74d9e3201d2c4925d1acb7aa614" ]; }
    { name = "netresearch_jsonmapper-3.1.1.0"; filename = "netresearch/jsonmapper/d8b9c0fb8b9bc08f7984c7635818f5fabfeec08d.zip"; sha256 = "81e18affc2316740c4ed91df6006d3b442de3f6f0f84ae5cdbc1d0f5888f920d"; urls = [ "https://api.github.com/repos/cweiske/jsonmapper/zipball/ba09f0e456d4f00cef84e012da5715625594407c" ]; }
    { name = "nikic_php-parser-4.4.0.0"; filename = "nikic/php-parser/d12c0cd58e6690c92e873cf2a150852242f61271.zip"; sha256 = "3925ae3eb126270bdb168145ee4a1260dea9a2ce810a047ff20a2ab9f1ee3b33"; urls = [ "https://api.github.com/repos/nikic/PHP-Parser/zipball/bd43ec7152eaaab3bd8c6d0aa95ceeb1df8ee120" ]; }
    { name = "nmred_kafka-php-0.1.5.0"; filename = "nmred/kafka-php/f5b2383008551fead59c6efbc8f4ac59a5971469.zip"; sha256 = "40c1f241e9d81a916e0760c8c96de722b0ef5af52d11d0a2fee276e18c0cf2e7"; urls = [ "https://api.github.com/repos/weiboad/kafka-php/zipball/317ad8c208684db8b9e6d2f5bf7f471e89a8b4eb" ]; }
    { name = "phan_phan-3.2.6.0"; filename = "phan/phan/a62d6c2cf72672c391f24c6dd1252091844663e2.zip"; sha256 = "04b0062141468873d0951369fa975fbbc06cfeb00c6907d9f9276685ce3a6106"; urls = [ "https://api.github.com/repos/phan/phan/zipball/e14110d4bef8643562b02a4003015c2c0dcc9fe4" ]; }
    { name = "phar-io_manifest-2.0.3.0"; filename = "phar-io/manifest/99001d1a4fa9041c56147e32147fb55de1cf9383.zip"; sha256 = "3cb072c02dc066ff22531c8bb5bdf1a4e1dca6207c378218f75c4f4680d4ed80"; urls = [ "https://api.github.com/repos/phar-io/manifest/zipball/97803eca37d319dfa7826cc2437fc020857acb53" ]; }
    { name = "phar-io_version-3.2.1.0"; filename = "phar-io/version/1495d1d88b1ae7e031b437037ce96298d897a969.zip"; sha256 = "4f6f4fab8bfeac95934cec75be23743e38b6d864876f52dcdd5b54e003fcab55"; urls = [ "https://api.github.com/repos/phar-io/version/zipball/4f7fd7836c6f332bb2933569e566a0d6c4cbed74" ]; }
    { name = "php-parallel-lint_php-console-color-0.3.0.0"; filename = "php-parallel-lint/php-console-color/777d5082378298a1fe062e2da34d7cd63c4bc2af.zip"; sha256 = "7364764828bf9047e12cd372ddadfc0337b786a6668cd9902f43f73b6b22040c"; urls = [ "https://api.github.com/repos/php-parallel-lint/PHP-Console-Color/zipball/b6af326b2088f1ad3b264696c9fd590ec395b49e" ]; }
    { name = "php-parallel-lint_php-console-highlighter-0.5.0.0"; filename = "php-parallel-lint/php-console-highlighter/590152ecfa35af37854361c0ab352e05f6253b15.zip"; sha256 = "c423d83f936025e27affb78912583f10b50f60cc0baf4b7735171a5b6e857704"; urls = [ "https://api.github.com/repos/php-parallel-lint/PHP-Console-Highlighter/zipball/21bf002f077b177f056d8cb455c5ed573adfdbb8" ]; }
    { name = "php-parallel-lint_php-parallel-lint-1.2.0.0"; filename = "php-parallel-lint/php-parallel-lint/694b9b4af36539c468ad42b77ec060f5b62152e1.zip"; sha256 = "cb535265c7a1b7e9bdd788af3cb91759ad883ca6e2abc54ad1fa61726e32714d"; urls = [ "https://api.github.com/repos/php-parallel-lint/PHP-Parallel-Lint/zipball/474f18bc6cc6aca61ca40bfab55139de614e51ca" ]; }
    { name = "phpdocumentor_reflection-common-2.2.0.0"; filename = "phpdocumentor/reflection-common/6243ab17e2330fb7ce63d34391d53104cc913dc0.zip"; sha256 = "39fca6dc8730bdc4f70c41e58e16595fc6695b4ae42327c32144c4131410a7f3"; urls = [ "https://api.github.com/repos/phpDocumentor/ReflectionCommon/zipball/1d01c49d4ed62f25aa84a747ad35d5a16924662b" ]; }
    { name = "phpdocumentor_reflection-docblock-5.3.0.0"; filename = "phpdocumentor/reflection-docblock/3c16e706c93df7017840bcf302eace70dc66a077.zip"; sha256 = "3664230b09277d49780b0cb8f0a4a324e061f4bad079ac015b49a3892f7440ef"; urls = [ "https://api.github.com/repos/phpDocumentor/ReflectionDocBlock/zipball/622548b623e81ca6d78b721c5e029f4ce664f170" ]; }
    { name = "phpdocumentor_type-resolver-1.6.1.0"; filename = "phpdocumentor/type-resolver/b1af375ec0f83ceb4e1ecffe10ffbb8532e8802a.zip"; sha256 = "247b237ec52823d5e4bb001a02a25d3207b3e9faf0d9a39ef12c577dcbf6cb78"; urls = [ "https://api.github.com/repos/phpDocumentor/TypeResolver/zipball/77a32518733312af16a44300404e945338981de3" ]; }
    { name = "phpspec_prophecy-1.15.0.0"; filename = "phpspec/prophecy/e54727a1db612d45086a4f2ae44776d299ac1679.zip"; sha256 = "1cf06a6e8a49538181d7107a9512a6bc3f44608cf22de8736e18694e45e887f7"; urls = [ "https://api.github.com/repos/phpspec/prophecy/zipball/bbcd7380b0ebf3961ee21409db7b38bc31d69a13" ]; }
    { name = "phpunit_php-code-coverage-7.0.15.0"; filename = "phpunit/php-code-coverage/4ba1e75b595ead0d26c0c8e1f4dac947fee223f2.zip"; sha256 = "d3c498a491077f33ffe80dd1f050fcfff18d6af5855bc47c036c9dabebdd71af"; urls = [ "https://api.github.com/repos/sebastianbergmann/php-code-coverage/zipball/819f92bba8b001d4363065928088de22f25a3a48" ]; }
    { name = "phpunit_php-file-iterator-2.0.5.0"; filename = "phpunit/php-file-iterator/2d2831bb7b3b93e29050baa8a2a05da3899e19b4.zip"; sha256 = "5ed1111f76eca01ccae96e9dfb336031e38cd4d529e6900a1f9babd6096b0bd7"; urls = [ "https://api.github.com/repos/sebastianbergmann/php-file-iterator/zipball/42c5ba5220e6904cbfe8b1a1bda7c0cfdc8c12f5" ]; }
    { name = "phpunit_php-text-template-1.2.1.0"; filename = "phpunit/php-text-template/2e483bd8277c3ff3905be9160b0938b306ac1069.zip"; sha256 = "e65c9271b5258e12b4beb258cff5e02da0aa72235b9c3695df4b6f8cd1a803f8"; urls = [ "https://api.github.com/repos/sebastianbergmann/php-text-template/zipball/31f8b717e51d9a2afca6c9f046f5d69fc27c8686" ]; }
    { name = "phpunit_php-timer-2.1.3.0"; filename = "phpunit/php-timer/d877c37f5e48f326e7da1e900ba042d001a60d23.zip"; sha256 = "ad6b272aa089cd4f63f54ee10fc0060438c007f8a3885bbf08c217f8f6c7ea89"; urls = [ "https://api.github.com/repos/sebastianbergmann/php-timer/zipball/2454ae1765516d20c4ffe103d85a58a9a3bd5662" ]; }
    { name = "phpunit_php-token-stream-4.0.4.0"; filename = "phpunit/php-token-stream/7a484df2a8888e20560d2ab3be66f42f03622296.zip"; sha256 = "016ab22d25f40e44be550fadeb58be2227d9442e04b2d8924e663558962e706e"; urls = [ "https://api.github.com/repos/sebastianbergmann/php-token-stream/zipball/a853a0e183b9db7eed023d7933a858fa1c8d25a3" ]; }
    { name = "phpunit_phpunit-8.5.26.0"; filename = "phpunit/phpunit/e2b096e7d50f4a1a56ea76bf317cc6701713dd91.zip"; sha256 = "babf3d1c58e0faa2db5212979f3a7d0eaca50997684805c21676940b324b2a69"; urls = [ "https://api.github.com/repos/sebastianbergmann/phpunit/zipball/ef117c59fc4c54a979021b26d08a3373e386606d" ]; }
    { name = "pimple_pimple-3.3.1.0"; filename = "pimple/pimple/0b3533af1f4df48a35116963872e1a4e91c1abc4.zip"; sha256 = "b8fc93ff48971031d86298f81a94cd48615ef23eb23f688796d6d30c1f4b52c2"; urls = [ "https://api.github.com/repos/silexphp/Pimple/zipball/21e45061c3429b1e06233475cc0e1f6fc774d5b0" ]; }
    { name = "psy_psysh-0.10.4.0"; filename = "psy/psysh/67de8afa0291ffe5137ee70655b46b7d9d671b67.zip"; sha256 = "6d1768e11bec9fbfbad967ca21b99a3c26314f23b53652a0c8627998464785ad"; urls = [ "https://api.github.com/repos/bobthecow/psysh/zipball/a8aec1b2981ab66882a01cce36a49b6317dc3560" ]; }
    { name = "sabre_event-5.1.4.0"; filename = "sabre/event/4c2391ff07e6968703a2170903ba7cdc7bd51f30.zip"; sha256 = "0a564ec62514691fc18861e795f6586e577643650575de55843d6294a58450c0"; urls = [ "https://api.github.com/repos/sabre-io/event/zipball/d7da22897125d34d7eddf7977758191c06a74497" ]; }
    { name = "sebastian_code-unit-reverse-lookup-1.0.2.0"; filename = "sebastian/code-unit-reverse-lookup/4dbb27a92c0b0cd57fcb8cfcf98d5ddb23711e6d.zip"; sha256 = "2a40d619b2899b5b78287135cec823945ad2d7f5c265aade864b3558b106c99c"; urls = [ "https://api.github.com/repos/sebastianbergmann/code-unit-reverse-lookup/zipball/1de8cd5c010cb153fcd68b8d0f64606f523f7619" ]; }
    { name = "sebastian_comparator-3.0.3.0"; filename = "sebastian/comparator/4820c115aa730390e1fcc41f6436710373849064.zip"; sha256 = "c336af6ce39b427c0a39eccfe3160e307eb992fffdb70000429a5853dcb65444"; urls = [ "https://api.github.com/repos/sebastianbergmann/comparator/zipball/1071dfcef776a57013124ff35e1fc41ccd294758" ]; }
    { name = "sebastian_diff-3.0.3.0"; filename = "sebastian/diff/c6bf355f27d05e7e224faaf785c2c1a365f75a40.zip"; sha256 = "228c390ddba8277d8b3aa1481a715e5b0ec4125275e444ebeb90bb089db38a5e"; urls = [ "https://api.github.com/repos/sebastianbergmann/diff/zipball/14f72dd46eaf2f2293cbe79c93cc0bc43161a211" ]; }
    { name = "sebastian_environment-4.2.4.0"; filename = "sebastian/environment/b4d76a035d8f2609a93b4c5ca32e5c987dcc4923.zip"; sha256 = "f7317f8f2772e770a4d047c31c56cad720410a35b5b92e138f4df495ce75bce8"; urls = [ "https://api.github.com/repos/sebastianbergmann/environment/zipball/d47bbbad83711771f167c72d4e3f25f7fcc1f8b0" ]; }
    { name = "sebastian_exporter-3.1.4.0"; filename = "sebastian/exporter/795286318b87707a287c812e612dcfd6a8916188.zip"; sha256 = "f385350a3c0fe2c3f9905cbbc8c54eae33b1518d6fddd67df19be83b7919359d"; urls = [ "https://api.github.com/repos/sebastianbergmann/exporter/zipball/0c32ea2e40dbf59de29f3b49bf375176ce7dd8db" ]; }
    { name = "sebastian_global-state-3.0.2.0"; filename = "sebastian/global-state/75df584325d9894a1eb26daf253b174f2330f6d5.zip"; sha256 = "598c654a47c5f6a82287a5724016d94f3fa3e414293827499e5a09a215010215"; urls = [ "https://api.github.com/repos/sebastianbergmann/global-state/zipball/de036ec91d55d2a9e0db2ba975b512cdb1c23921" ]; }
    { name = "sebastian_object-enumerator-3.0.4.0"; filename = "sebastian/object-enumerator/92cc598970b1cc2a000e1056aaaa829515724193.zip"; sha256 = "9c8084918df164cdbca8390d0ae8edd7af4f8c8db051f237f7734001243ae781"; urls = [ "https://api.github.com/repos/sebastianbergmann/object-enumerator/zipball/e67f6d32ebd0c749cf9d1dbd9f226c727043cdf2" ]; }
    { name = "sebastian_object-reflector-1.1.2.0"; filename = "sebastian/object-reflector/5f8896b418aef6939b34fda71dc35ee59b044dc5.zip"; sha256 = "e887906bb0d427a3bb38a46b6656fed2b32e8e4e6df360f96230e8e1664d0f04"; urls = [ "https://api.github.com/repos/sebastianbergmann/object-reflector/zipball/9b8772b9cbd456ab45d4a598d2dd1a1bced6363d" ]; }
    { name = "sebastian_recursion-context-3.0.1.0"; filename = "sebastian/recursion-context/caf8067cd91960cd4eced9e40f6668440c44bf08.zip"; sha256 = "475f91729bbdd3599a43c64bf284dc106d61c56f05482ba15f96bf2a2606f8fe"; urls = [ "https://api.github.com/repos/sebastianbergmann/recursion-context/zipball/367dcba38d6e1977be014dc4b22f47a484dac7fb" ]; }
    { name = "sebastian_resource-operations-2.0.2.0"; filename = "sebastian/resource-operations/c51f0469858a579ba5faa2b1476120b8b3def87d.zip"; sha256 = "cd75cd6e00850f10fba63fe3355eb316afbeddb2c6921c206b92cc9450463582"; urls = [ "https://api.github.com/repos/sebastianbergmann/resource-operations/zipball/31d35ca87926450c44eae7e2611d45a7a65ea8b3" ]; }
    { name = "sebastian_type-1.1.4.0"; filename = "sebastian/type/3c2f920c66eeed28f47dff8fee8cf02df8881362.zip"; sha256 = "3f373a0389b0c842d18252d0d5f206b0103eab1df1db06fa8d82410c918a654f"; urls = [ "https://api.github.com/repos/sebastianbergmann/type/zipball/0150cfbc4495ed2df3872fb31b26781e4e077eb4" ]; }
    { name = "sebastian_version-2.0.1.0"; filename = "sebastian/version/c315a200d32565a6d8ebb3495cb5ae34c5ced3c8.zip"; sha256 = "473af38d01bed9c8b3a340bf1b34879b65f7ac852ee404af2a0f8a3f352c3c73"; urls = [ "https://api.github.com/repos/sebastianbergmann/version/zipball/99732be0ddb3361e16ad77b68ba41efc8e979019" ]; }
    { name = "squizlabs_php_codesniffer-3.6.1.0"; filename = "squizlabs/php_codesniffer/34f1dfea39f06111c930967d7ecece596c9ff4bc.zip"; sha256 = "9f8afbe0bbc22e4321cfb4bf5fcff660e7c28d6c14e98dcb8b3e6b61a38866a0"; urls = [ "https://api.github.com/repos/squizlabs/PHP_CodeSniffer/zipball/f268ca40d54617c6e06757f83f699775c9b3ff2e" ]; }
    { name = "symfony_console-5.4.7.0"; filename = "symfony/console/842bd514b2abfd410fc49c86e189faf6f858afda.zip"; sha256 = "100c4b62e19071966b007a0bad7731fee72cc81f0e479308cff4425c6cae0d3b"; urls = [ "https://api.github.com/repos/symfony/console/zipball/900275254f0a1a2afff1ab0e11abd5587a10e1d6" ]; }
    { name = "symfony_deprecation-contracts-3.0.0.0"; filename = "symfony/deprecation-contracts/22f9a768c9b325689cfaba1f46cbc9014939f71f.zip"; sha256 = "4fabc2f753289e5fb03129cfc713c7cf4d10eadc263cd8fef85e3e8ef2d3ed89"; urls = [ "https://api.github.com/repos/symfony/deprecation-contracts/zipball/c726b64c1ccfe2896cb7df2e1331c357ad1c8ced" ]; }
    { name = "symfony_polyfill-intl-grapheme-1.25.0.0"; filename = "symfony/polyfill-intl-grapheme/b5d0e20ecbe89643204b46e7948a397defea34a3.zip"; sha256 = "f9f4178da37184e47b6fe691ab51eeea660fc3171bd966668bd99f53a2abbeb7"; urls = [ "https://api.github.com/repos/symfony/polyfill-intl-grapheme/zipball/81b86b50cf841a64252b439e738e97f4a34e2783" ]; }
    { name = "symfony_polyfill-php73-1.25.0.0"; filename = "symfony/polyfill-php73/e4458bbc9428524959c1f1bd629191e1c898dbf0.zip"; sha256 = "1e1100a4712be430b9a1987c63a2dc95682f81c21b48747800abd88ca072e613"; urls = [ "https://api.github.com/repos/symfony/polyfill-php73/zipball/cc5db0e22b3cb4111010e48785a97f670b350ca5" ]; }
    { name = "symfony_service-contracts-2.2.0.0"; filename = "symfony/service-contracts/bb6eea1b73c5abea3ff1a1beaa1e198c96b92592.zip"; sha256 = "8287ba33c2709c2b784eace50c0b1452c504543b4103896059b8647169c01199"; urls = [ "https://api.github.com/repos/symfony/service-contracts/zipball/d15da7ba4957ffb8f1747218be9e1a121fd298a1" ]; }
    { name = "symfony_string-6.0.3.0"; filename = "symfony/string/011bb285700e81cc751bcc018f81e02a509831c4.zip"; sha256 = "617009fa198c38576cabef0cf033afe63e1931756a2d454662b3b68d0f685d3e"; urls = [ "https://api.github.com/repos/symfony/string/zipball/522144f0c4c004c80d56fa47e40e17028e2eefc2" ]; }
    { name = "symfony_var-dumper-5.4.6.0"; filename = "symfony/var-dumper/83d386a3004ece19bd08ad380f8cb047252c5a06.zip"; sha256 = "66cafaab68984324d955f1a07d3405b80fd576048846a08d20603b5fceea2116"; urls = [ "https://api.github.com/repos/symfony/var-dumper/zipball/294e9da6e2e0dd404e983daa5aa74253d92c05d0" ]; }
    { name = "symfony_yaml-5.0.11.0"; filename = "symfony/yaml/c74575f7ebc396e0f655c86899d7266d74c45065.zip"; sha256 = "25d41ae3990a40a29e6378e1faa275fbb2e43fc4b6f5f2509c01ce446789fa94"; urls = [ "https://api.github.com/repos/symfony/yaml/zipball/29b60e88ff11a45b708115004fdeacab1ee3dd5d" ]; }
    { name = "theseer_tokenizer-1.2.1.0"; filename = "theseer/tokenizer/9c419ba4ed9d43ff57a21270f44363ad0bed22f7.zip"; sha256 = "18d8c32441b19070ed7643321f5d3d5ee07217b991bee605cf64c979025044fd"; urls = [ "https://api.github.com/repos/theseer/tokenizer/zipball/34a41e998c2183e22995f158c581e7b5e755ab9e" ]; }
    { name = "webmozart_assert-1.10.0.0"; filename = "webmozart/assert/9badd292a512316673890927d579f69ae6c75984.zip"; sha256 = "c4b0eb77a1af07776537f7e674fc0954cd1dde71b27542d76327f3c9c582b89f"; urls = [ "https://api.github.com/repos/webmozarts/assert/zipball/6964c76c7804814a842473e0c8fd15bab0f18e25" ]; }
    { name = "wikimedia_avro-1.9.0.0"; filename = "wikimedia/avro/e0cc4607972c0b044543cffbc1a380636f229765.zip"; sha256 = "cbc0dd036d0d691a7e65b1b6285d66a72dbf89b91217823e4bb922a33fd8ba6e"; urls = [ "https://api.github.com/repos/wikimedia/avro-php/zipball/b2e0c9d750da03d95ba979215397f62a6121ddea" ]; }
    { name = "wikimedia_testing-access-wrapper-2.0.0.0"; filename = "wikimedia/testing-access-wrapper/03084593538e78da4be9d57953177ba22c269afd.zip"; sha256 = "520573e061430656069f7c8c3016dfccba221a7ec09f074d9aa146cd8aefd4c5"; urls = [ "https://api.github.com/repos/wikimedia/testing-access-wrapper/zipball/280e613c76f481f2fe90e0ea22361080b6ab0d65" ]; }
    { name = "wmde_hamcrest-html-matchers-0.1.1.0"; filename = "wmde/hamcrest-html-matchers/fded5c8446ff6d9b9f45fbc1d82365c79afc1132.zip"; sha256 = "2244c6bdad136919d2c107f57c184bf61642d849290fc22e832ce14b2be58372"; urls = [ "https://api.github.com/repos/wmde/hamcrest-html-matchers/zipball/89e15f78c22535891318a4dd7580c63d83c766c6" ]; }
  ];
  localPackages = [
  ];

  # Shell snippet to collect all project dependencies.
  collectCacheScript = writeText "collect-cache.sh" (
    concatMapStrings (args: ''
      (
        cacheFile=${escapeShellArg args.filename}
        cacheFilePath="$COMPOSER_CACHE_DIR/files/$cacheFile"
        mkdir -p "$(dirname "$cacheFilePath")"
        cp ${escapeShellArg (fetcher args)} "$cacheFilePath"
      )
    '') cacheEntries
  );

  replaceLocalPaths = writeText "replace-local-paths.sh" (
    concatMapStrings (args: ''
      sed -i -e "s|\"${args.string}\"|\"${args.path}\"|" composer.lock
    '') localPackages
  );

in stdenv.mkDerivation {
  name = "mediawiki_core";
  inherit src;

  # Make sure the build uses the right PHP version everywhere.
  # Also include unzip for Composer.
  buildInputs = [ php unzip ];

  # Defines the shell alias to run Composer.
  postHook = ''
    composer () {
      php "$NIX_COMPOSER_PATH" "$@"
    }
  '';

  configurePhase = ''
    runHook preConfigure

    # Set the cache directory for Composer.
    export COMPOSER_CACHE_DIR="$NIX_BUILD_TOP/.composer/cache"

    # Build the cache directory contents.
    source ${collectCacheScript}

    # Replace local package paths with their Nix store equivalent.
    source ${replaceLocalPaths}

    # Store the absolute path to Composer for the 'composer' alias.
    export NIX_COMPOSER_PATH="$(readlink -f ${escapeShellArg composerPath})"

    # Run normal Composer install to complete dependency installation.
    composer install

    runHook postConfigure
  '';

  buildPhase = ''
    runHook preBuild
    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out/libexec $out/bin

    # Move the entire project to the output directory.
    mv $PWD "$out/libexec/$sourceRoot"
    cd "$out/libexec/$sourceRoot"

    # Update the path to Composer.
    export NIX_COMPOSER_PATH="$(readlink -f ${escapeShellArg composerPath})"

    # Invoke a plugin internal command to setup binaries.
    composer nixify-install-bin "$out/bin"

    runHook postInstall
  '';

  passthru = {
    inherit php;
  };
}
