# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.nix]
# Formatter to run
command = "nixfmt"
# Command-line arguments for the command
options = [ "--verify" ]
# Glob pattern of files to include
includes = [ "*.nix" ]
# Glob patterns of files to exclude
excludes = []
